// <auto-generated />
using BookstoreManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookstoreManagementSystem.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    partial class BookstoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.35");

            modelBuilder.Entity("BSMSShared.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Charles Darwin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Richard Dawkins"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rachel Carson"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Carl Sagan"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("BSMSShared.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Price = 250,
                            Title = "On the origin of Species"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Price = 300,
                            Title = "The Selfish Gene"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Price = 350,
                            Title = "Silent Spring"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            Price = 400,
                            Title = "Cosmos"
                        });
                });

            modelBuilder.Entity("BSMSShared.Models.Book", b =>
                {
                    b.HasOne("BSMSShared.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
